In [1]:
import numpy as np

In [7]:
streetlights = np.array([[1, 0, 1], 
                         [0, 1, 1], 
                         [0, 0, 1], 
                         [1, 1, 1], 
                         [0, 1, 1], 
                         [1, 0, 1]])
streetlights

array([[1, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [8]:
walk_stop = np.array([0, 1, 0, 1, 1, 0]).reshape(6, 1)
walk_stop

array([[0],
       [1],
       [0],
       [1],
       [1],
       [0]])

In [87]:
inputs_shape = streetlights.shape

In [88]:
weights = np.random.randn(inputs_shape[1])

In [89]:
weights

array([-0.9615111 ,  0.67083958, -1.60334659])

In [99]:
weights.dot(streetlights[0])

-0.34015028719692764

In [100]:
def neural_network(input, weights):
    return input.dot(weights)

In [101]:
def mse(pred, true):
    return (pred-true) ** 2

In [102]:
alpha = 0.1

for iteration in range(100):
    error_for_all_lights = 0 
    for idx in range(len(walk_stop)):
        input = streetlights[idx]
        label = walk_stop[idx]
        pred = neural_network(input, weights)
        
        error = mse(pred, label)
        error_for_all_lights += error

        delta = pred - label
        weights = weights - (alpha * (delta * input))
        print(f'Predictions: {pred}')
    print(f'Error: {error}')
        


Predictions: -0.34015028719692764
Predictions: 0.2138617207437531
Predictions: -0.3783640303095492
Predictions: 0.5937834081035893
Predictions: 0.49016909800523956
Predictions: -0.02344359022220427
Error: [0.0005496]
Predictions: -0.018754872177763393
Predictions: 0.5963551246441884
Predictions: -0.2043385441138992
Predictions: 0.9272170880340104
Predictions: 0.7120745365199386
Predictions: 0.08914357294596442
Error: [0.00794658]
Predictions: 0.07131485835677154
Predictions: 0.7536137860856772
Predictions: -0.1392410738967455
Predictions: 1.0377467182318112
Predictions: 0.809265792611854
Predictions: 0.10713869255897643
Error: [0.0114787]
Predictions: 0.08571095404718113
Predictions: 0.8281276694288675
Predictions: -0.11211594919493997
Predictions: 1.071585675952386
Predictions: 0.8593965952721108
Predictions: 0.09671079649666384
Error: [0.00935298]
Predictions: 0.07736863719733107
Predictions: 0.8701093328482891
Predictions: -0.09842145805212406
Predictions: 1.0792350466090037
Predict

In [106]:
validation = np.array([1, 1, 0])

In [107]:
val_pred = neural_network(validation, weights)

In [111]:
print(f'Prediction: {val_pred:.1f}')

Prediction: 1.0


In [112]:
weights

array([ 9.86879094e-05,  1.00009916e+00, -1.14194979e-04])